# Experimental Design
_It is the process by which we carry out research in an objective & controlled fashion._
## Definitions
**Subjects**: (what we're experimenting on- could be people/ users/ students etc.) can be divided into 2 test groups:
- **Treatment group:** group to which one changes are given; the group to be studied

- **Control group:** not given any change (the placebo group) ; results already known for this group

In [1]:
import  pandas as pd
import numpy as np

In [2]:
hw_main = pd.read_csv('./datasets/weightsheights.csv')
hw_main.head()

,Height(Inches),Weight(Pounds),Height in cm,Weight in kg,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,category
0,65.78331,112.9925,167.089517,51.252597,2.0,160,0.393701,170.0,160-170
1,71.51521,136.4873,181.648535,61.909672,NaN,180,NaN,190.0,180-190
2,69.39874,153.0269,176.272704,69.411917,NaN,180,NaN,190.0,180-190
3,68.21660,142.3354,173.270070,64.562328,NaN,170,NaN,180.0,170-180
4,67.78781,144.2971,172.180944,65.452141,NaN,170,NaN,180.0,170-180

In [3]:
# extracting only the heights column
heights = hw_main[['Height in cm']]
heights.head()

   Height in cm
0    167.089517
1    181.648535
2    176.272704
3    173.270070
4    172.180944

## Assigning subjects to groups

**Non-random assignment**
- Split the dataframe manually using `.iloc`<br>
    Example: splitting a dataframe with 1K rows into `iloc[0:050]` & `iloc[501:1000]`

In [4]:
nonrandom_g1 = heights.iloc[0:(len(heights)//2)]
nonrandom_g2 = heights.iloc[(len(heights)//2):]
compare_nr = pd.concat([nonrandom_g1['Height in cm'].describe(), nonrandom_g2['Height in cm'].describe()], axis=1)
print(compare_nr)

       Height in cm  Height in cm
count  12500.000000  12500.000000
mean     172.668017    172.736814
std        4.838883      4.821573
min      153.956048    153.106952
25%      169.357926    169.507805
50%      172.676676    172.754502
75%      175.915257    176.002468
max      190.888009    190.116103

>**Random assignment**
- Using `.sample()` method with no replacement

Definition :
>Randomization is **the process of assigning experimental units to treatment groups using a random mechanism**, so that treatment assignment is independent of subjects' pre-existing characteristics.

Its purpose :
>Its primary purpose is to reduce systematic differences between treatment groups and prevent confounding, allowing differences in outcomes to be more credibly attributed to the treatment.

Since it makes treatment assignment independent of potential confounding variables, atleast in expectation that is why randomized controlled experiments are considered the strongest standard design for establishing causal effects.

**NOTE:** It does NOT guarantee identical groups.<br>
It only **guarantees a random assignment mechanism** and not perfect balance in every sample.

In [5]:
random_g1 = heights.sample(frac=0.5, replace=False, random_state=42)
# in Group-2 consider only unique rows not considered in Group-1 
random_g2 = heights.drop(random_g1.index)
compare_rd = pd.concat([random_g1['Height in cm'].describe(), random_g2['Height in cm'].describe()], axis=1)
print(compare_rd)

       Height in cm  Height in cm
count  12500.000000  12500.000000
mean     172.697820    172.707011
std        4.842663      4.818017
min      154.447665    153.106952
25%      169.447760    169.423268
50%      172.722129    172.698634
75%      175.946962    175.966939
max      190.792480    190.888009

>Thus we can say Randomization is best method to 


### What happens if data is not randomized?
Randomization makes assignment independent of the characteristics of the participants, on average.